[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"

[functions]
  external_node_modules = ["@supabase/ssr", "@supabase/supabase-js"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
